server:
  port: ${SERVER_PORT:9001}
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false

spring:
  jmx:
    enabled: true
    default_domain: Kafdrop
  jackson:
    deserialization:
      fail_on_unknown_properties: false
      read_unknown_enum_values_as_null: true

management:
  endpoints:
    web:
      base-path: /actuator
      exposure.include: "*"
  server:
    port: 9001

kafdrop.monitor:
  clientId: Kafdrop

kafka:
  brokerConnect: 10.101.104.105:31090,10.101.104.106:31090,10.101.104.107:31090
  isSecured: false
  saslMechanism: "PLAIN"
  securityProtocol: "SASL_PLAINTEXT"
  truststoreFile: "${KAFKA_TRUSTSTORE_FILE:kafka.truststore.jks}"
  propertiesFile : "${KAFKA_PROPERTIES_FILE:kafka.properties}"
  keystoreFile: "${KAFKA_KEYSTORE_FILE:kafka.keystore.jks}"
